hack visiting ivc node
Midnight relation: 6248 public inputs, 6327 total inputs

thread 'main' panicked at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/verifier/expressions/mod.rs:44:13:
Virtual selector are removed during optimisation
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: midnight_circuits::verifier::expressions::eval_expression
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/verifier/expressions/mod.rs:44:13
   3: midnight_circuits::verifier::expressions::eval_expression
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/verifier/expressions/mod.rs:60:24
   4: midnight_circuits::verifier::verifier_gadget::VerifierGadget<S>::verify_algebraic_constraints
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/verifier/verifier_gadget.rs:451:38
   5: midnight_circuits::verifier::verifier_gadget::VerifierGadget<S>::prepare
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/verifier/verifier_gadget.rs:650:9
   6: midnight_circuits::compact_std_lib::ZkStdLib::verifier_prepare_partial_plonk
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/compact_std_lib.rs:796:9
   7: circ::target::halo2::trans::ToMidnight<L>::embed_ivc
             at ./src/target/halo2/trans.rs:744:29
   8: circ::target::halo2::trans::ToMidnight<L>::assert_bool
             at ./src/target/halo2/trans.rs:1735:29
   9: circ::target::halo2::trans::ToMidnight<L>::assert_bool
             at ./src/target/halo2/trans.rs:1812:17
  10: <circ::target::halo2::trans::IrRelation as midnight_circuits::compact_std_lib::Relation>::circuit
             at ./src/target/halo2/trans.rs:1955:13
  11: <midnight_circuits::compact_std_lib::MidnightCircuit<R> as midnight_proofs::plonk::circuit::Circuit<midnight_curves::fq::Fq>>::synthesize
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/compact_std_lib.rs:1670:9
  12: <midnight_proofs::circuit::floor_planner::single_pass::SimpleFloorPlanner as midnight_proofs::plonk::circuit::FloorPlanner>::synthesize
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/proofs/src/circuit/floor_planner/single_pass.rs:35:9
  13: midnight_proofs::plonk::keygen::k_from_circuit::{{closure}}
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/proofs/src/plonk/keygen.rs:237:13
  14: core::iter::traits::iterator::Iterator::find::check::{{closure}}
             at /private/tmp/nix-build-rustc-1.88.0.drv-0/rustc-1.88.0-src/library/core/src/iter/traits/iterator.rs:2858:20
  15: core::iter::traits::iterator::Iterator::try_fold
             at /private/tmp/nix-build-rustc-1.88.0.drv-0/rustc-1.88.0-src/library/core/src/iter/traits/iterator.rs:2400:21
  16: core::iter::traits::iterator::Iterator::find
             at /private/tmp/nix-build-rustc-1.88.0.drv-0/rustc-1.88.0-src/library/core/src/iter/traits/iterator.rs:2862:9
  17: midnight_proofs::plonk::keygen::k_from_circuit
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/proofs/src/plonk/keygen.rs:208:10
  18: midnight_proofs::plonk::keygen::keygen_vk
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/proofs/src/plonk/keygen.rs:262:13
  19: midnight_circuits::utils::plonk_api::BlstPLONK<Relation>::setup_vk
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/utils/plonk_api.rs:70:26
  20: midnight_circuits::compact_std_lib::setup_vk
             at /Users/julian/.cargo/git/checkouts/midnight-zk-da166a90e27a77d3/e4f6770/circuits/src/compact_std_lib.rs:1722:14
  21: zxc::main
             at ./examples/zxc.rs:2947:14
  22: core::ops::function::FnOnce::call_once
             at /private/tmp/nix-build-rustc-1.88.0.drv-0/rustc-1.88.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.